#!/bin/bash

# mount cifs on Hyper-V
sed -i '/medical-insight/d' /etc/fstab
mkdir -p /mnt/usb/medical-insight
echo -e "\n//192.168.56.1/medical-insight /mnt/usb/medical-insight cifs username=guest,iocharset=utf8" | sudo tee -a /etc/fstab
mount -a
