#!/bin/bash

USB_HOME=/mnt/usb/medical-insight
APP_HOME=/home/airuntime

# stdin pw
echo '!skcc1234' | sudo -S $USB_HOME/install/init

sleep 3s

# 설치파일 복사
sudo cp $USB_HOME/medical-insight $APP_HOME
sudo cp -R $USB_HOME/install $APP_HOME
sudo cp -R $USB_HOME/network-driver $APP_HOME
sudo cp -R $USB_HOME/kubernetes $APP_HOME
sudo cp -R $USB_HOME/aiip-runtime $APP_HOME
sudo cp -R $USB_HOME/test $APP_HOME

sudo chown -R airuntime:airuntime $APP_HOME

cd $APP_HOME

# network driver
. $APP_HOME/install/network-driver

# Timezone setup
sudo ln -sf /usr/share/zoneinfo/Asia/Seoul /etc/localtime
sudo apt-get update
sudo apt-get install rdate pv -y
sudo rdate -s time.bora.net

echo "========================================================================================================"
echo "Timezone setup completed."
echo "--------------------------------------------------------------------------------------------------------"
date
echo "========================================================================================================"
sleep 3s

# swap off
sudo swapon --show
sudo free -h
sudo swapoff -a
sudo rm -f /swap.img
checkval="/swap.img"
sudo sed -i 's/\/swap.img/\# \/swap.img/g' /etc/fstab
sudo swapon --show

# docker
sudo apt-get update
sudo apt-get install docker.io apt-transport-https gnupg-agent conntrack -y
sudo adduser `id -un` docker
sudo chmod 777 /var/run/docker.sock

echo "========================================================================================================"
echo "docker installed."
echo "--------------------------------------------------------------------------------------------------------"
docker version
echo "--------------------------------------------------------------------------------------------------------"
ls -al /var/run/docker.sock
echo "========================================================================================================"
sleep 3s

# install k9s, minikube, kubectl, istioctl
sudo chmod +x $APP_HOME/kubernetes/bin/*
sudo install $APP_HOME/kubernetes/bin/* /usr/local/bin/

echo "========================================================================================================"
echo "k9s minikube kubectl istioctl installed."
echo "--------------------------------------------------------------------------------------------------------"
which k9s
which minikube
which kubectl
which istioctl
echo "========================================================================================================"
sleep 3s

# java
# install the necessary dependencies
sudo apt-get -q update
sudo apt-get -yq install gnupg curl -y

# add Azul's public key
sudo apt-key adv \
  --keyserver hkp://keyserver.ubuntu.com:80 \
  --recv-keys 0xB1998361219BD9C9

# download and install the package that adds 
# the Azul APT repository to the list of sources 
curl -O https://cdn.azul.com/zulu/bin/zulu-repo_1.0.0-2_all.deb

# install the package
sudo apt-get install ./zulu-repo_1.0.0-2_all.deb

# update the package sources
sudo apt-get update

# install Azul Zulu JDK 11
sudo apt-get install zulu11-jdk -y

echo "========================================================================================================"
echo "java installed."
echo "--------------------------------------------------------------------------------------------------------"
java -version
echo "========================================================================================================"
sleep 3s

# install redis
sudo apt-get update
sudo apt-get install redis-server -y
sudo sed -i 's/\# requirepass foobared/requirepass \!skcc1234/g' /etc/redis/redis.conf
sudo systemctl restart redis-server

echo "========================================================================================================"
echo "redis installed."
echo "--------------------------------------------------------------------------------------------------------"
redis-cli --version
echo "========================================================================================================"
sleep 3s

# install nginx
#sudo apt-get update
#sudo apt-get install nginx -y
#sudo cp /mnt/usb/medical-insight/3.aiip-runtime/nginx.conf /etc/nginx/nginx.conf

# install mariadb
sudo apt-get update
sudo apt-get install mariadb-server -y

# initial data migration
cat $APP_HOME/aiip-runtime/createDB.sql | sudo mysql -u root
cat $APP_HOME/aiip-runtime/v1_airuntime_20210727_060001.sql | mysql -u airuntime --password='!skcc1234' airuntime

echo "========================================================================================================"
echo "MariaDB installed."
echo "--------------------------------------------------------------------------------------------------------"
mysql --version
echo "========================================================================================================"
sleep 3s

sudo apt-get update
sudo apt-get install jq python3-pip -y
sudo pip install watchdog

echo "========================================================================================================"
echo "pip install watchdog completed."
echo "--------------------------------------------------------------------------------------------------------"
pip --version
pip list | grep watchdog
echo "========================================================================================================"
sleep 3s

# create working directory
sudo mkdir -p /data/pacs/input /data/pacs/output /data/pacs/backup /data/pacs/tmp /data/airuntime/config /data/airuntime/www/predict/history
sudo chown -R airuntime:airuntime /data
sudo chmod -R 777 /data
sudo ln -s /data/pacs /pacs
sudo ln -s /data/airuntime/www /www
echo "========================================================================================================"
echo "make directories completed."
echo "--------------------------------------------------------------------------------------------------------"
du -h /data
echo "========================================================================================================"
sleep 5s

# setup nfs
sudo apt-get update
sudo apt-get install nfs-kernel-server -y
#sudo echo -e "\n/data/pacs/ *(rw,sync,insecure,no_subtree_check,no_root_squash)" >> /etc/exports
echo -e "\n/data/pacs/ *(rw,sync,insecure,no_subtree_check,no_root_squash)" | sudo tee -a /etc/exports
sudo exportfs -a
sudo systemctl restart nfs-kernel-server
echo "========================================================================================================"
echo "NFS setup completed."
echo "--------------------------------------------------------------------------------------------------------"
sudo systemctl status nfs-kernel-server
echo "--------------------------------------------------------------------------------------------------------"
sudo cat /etc/exports
echo "========================================================================================================"
sleep 5s

# minikube 시작
cd ~
minikube start --kubernetes-version=v1.18.17 --driver=none --apiserver-ips 127.0.0.1 --apiserver-name localhost && \
minikube status

echo "========================================================================================================"
echo "Creating minikube cluster. Wait for 1 min."
echo "========================================================================================================"
for x in {1..60} ; do
    sleep 1s
    printf .
done | pv -pt -i0.2 -s60 -w 80 > /dev/null

# cert mgr, istio
kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v0.15.1/cert-manager.yaml
istioctl install -y

echo "========================================================================================================"
echo "Deploying Cert-manager & Istio. it takes 30s."
echo "========================================================================================================"
for x in {1..30} ; do
    sleep 1s
    printf .
done | pv -pt -i0.2 -s30 -w 80 > /dev/null

# minikube로 구성된 K8S에 LoadBalancer 타입으로 서비스를 배포하면, External IP할당이 되지 않는다.
# NodePort 타입으로 변경하여 해결.
echo "========================================================================================================"
echo "type of istio-ingressgateway changed."
echo "========================================================================================================"
kubectl -n istio-system get svc istio-ingressgateway
kubectl -n istio-system get svc istio-ingressgateway -o yaml | sed "s/type: LoadBalancer/type: NodePort/g" | kubectl replace -f -
echo "--------------------------------------------------------------------------------------------------------"
kubectl -n istio-system get svc istio-ingressgateway
echo "========================================================================================================"
sleep 5s

# web 소스 빌드
#sudo apt-get update
#sudo apt-get install npm -y
#cd /home/airuntime/aiip-runtime/airuntime-web
#sed -i "s/gateway/$(hostname -I | awk '{print $1}')/g" /home/airuntime/aiip-runtime/airuntime-web/.env.release
#npm install
#npm run build

# web 소스 적용
#sudo rsync -avz ./dist/* \
#  /usr/share/nginx/html/airuntime-web && \
#sudo chown -R www-data:www-data /usr/share/nginx/html/airuntime-web && \
#sudo systemctl restart nginx


# setup ingress host, ip
cp $APP_HOME/aiip-runtime/config/common-stg.yml /data/airuntime/config/
sed -i "s/192.168.1.31/$(hostname -I | awk '{print $1}')/g" /data/airuntime/config/common-stg.yml
sed -i "s/99999/$(kubectl -n istio-system get svc istio-ingressgateway -o yaml | grep -B 2 'port: 80' | grep 'nodePort' | awk '{print $2}')/g" /data/airuntime/config/common-stg.yml

# minikube는 api server 포트가 8443으로 되어 있어서 443 -> 8443 포트포워딩 필요
sudo iptables -t nat -A OUTPUT -o lo -p tcp --dport 443 -j REDIRECT --to-port 8443

# knative-serving
kubectl apply -f $APP_HOME/kubernetes/knative-serving/serving-crds.yaml
kubectl apply -f $APP_HOME/kubernetes/knative-serving/serving-core.yaml
kubectl apply -f $APP_HOME/kubernetes/knative-serving/net-certmanager-release.yaml
kubectl apply -f $APP_HOME/kubernetes/knative-serving/net-istio-release.yaml

echo "========================================================================================================"
echo "Deploying knative-serving. it takes 1m."
echo "========================================================================================================"
for x in {1..60} ; do
    sleep 1s
    printf .
done | pv -pt -i0.2 -s60 -w 80 > /dev/null

# kfserving
kubectl apply -f $APP_HOME/kubernetes/kfserving.yaml

echo "========================================================================================================"
echo "Deploying kfserving. it takes 1m."
echo "========================================================================================================"
for x in {1..60} ; do
    sleep 1s
    printf .
done | pv -pt -i0.2 -s60 -w 80 > /dev/null

# knative와 kfserving 버전 호환 문제로 임시 조치
kubectl -n kfserving-system get cm inferenceservice-config -o yaml | sed "s/cluster-local-gateway/knative-local-gateway/g" | kubectl replace -f -

cp $APP_HOME/aiip-runtime/airuntime-watcher/nfs-pv.yml /data/airuntime/
sed -i "s/192.168.1.31/$(hostname -I | awk '{print $1}')/g" /data/airuntime/nfs-pv.yml
kubectl create namespace auto-create-26
kubectl -n auto-create-26 apply -f /data/airuntime/nfs-pv.yml

echo "========================================================================================================"
echo "Creating pv. it takes 10s."
echo "========================================================================================================"
for x in {1..10} ; do
    sleep 1s
    printf .
done | pv -pt -i0.2 -s10 -w 80 > /dev/null

# setup service deamon
sudo cp $APP_HOME/aiip-runtime/serviced/* /etc/systemd/system/
sudo systemctl enable airuntime-configserver.service
sudo systemctl enable airuntime-gateway.service
sudo systemctl enable airuntime-account.service
#sudo systemctl enable airuntime-monitoring.service
#sudo systemctl enable airuntime-history.service
sudo systemctl enable airuntime-core.service
sudo systemctl enable airuntime-ifservice.service
sudo systemctl enable airuntime-watcher.service

echo "========================================================================================================"
echo "AI Runtime Backend Servives are running."
# backend svc run
sudo systemctl start airuntime-configserver.service
sleep 3s
sudo systemctl start airuntime-gateway.service
sudo systemctl start airuntime-account.service
#sudo systemctl start airuntime-monitoring.service
#sudo systemctl start airuntime-history.service
sudo systemctl start airuntime-core.service
sudo systemctl start airuntime-ifservice.service

ps -ef | grep -v grep | grep "java -jar"
echo "========================================================================================================"
echo "Waiting for 20s."
echo "========================================================================================================"
for x in {1..20} ; do
    sleep 1s
    printf .
done | pv -pt -i0.2 -s20 -w 80 > /dev/null

# deploy
# 연동 중지
sudo systemctl stop airuntime-watcher.service
cp $APP_HOME/aiip-runtime/config/watcher.conf $APP_HOME/aiip-runtime/airuntime-watcher/src/

echo "========================================================================================================"
echo "Deploying AI Model(Brain Hemorrhage Detection Solution). it takes 6m."
echo "========================================================================================================"
ip_addr=$(hostname -I | awk '{print $1}')
token=$(curl --location --request POST "http://$ip_addr:17000/api/auth/issueToken" \
--header 'Content-Type: application/json' \
--data-raw '{
    "accessKey": "04f23bfa-80e0-4da9-a0e1-19e75ac87e48" 
}' | jq '.token' | sed 's/"//g')
echo ""

# 기존 정보 삭제
sed -i '/inferenceId/d' $APP_HOME/aiip-runtime/airuntime-watcher/src/watcher.conf

# 모델 배포
echo "inferenceId = $( \
curl --location --request POST "http://$ip_addr:17000/api/core/models/deployment?account_id=26&account_id=26" \
--header 'Content-Type: application/json' \
--header "Authorization: $token" \
--data-raw '{
  "account_id": 26,
  "description": "Brain Hemorrhage Detection Solution, SKH-BCH-001, v 2.0.0",
  "metadata": {
    "name": "skh-bch-001",
    "k8s_ns_nm": "auto-create-26",
    "concurrent": 1
  },
  "predictor": {
    "type": "custom",
    "minReplicas": 1,
    "maxReplicas": 1,
    "custom": {
      "container": {
        "image": "wxmaseve/skh-bch:0.0.1.onpremise-triage",
        "resources": {
          "limits": {
            "cpu": 2,
            "memory": 4,
            "gpu": 0
          },
          "requests": {
            "cpu": 2,
            "memory": 4,
            "gpu": 0
          }
        },
        "optional_json": "{\n    \"env\": [{\n            \"name\": \"STORAGE_URI\",\n            \"value\": \"pvc://on-nfs-pvc\"\n        },\n        {\n            \"name\": \"MODEL_NAME\",\n            \"value\": \"skh-bch-001\"\n        }\n    ],\n    \"args\": [\n        \"--model_name=$(MODEL_NAME)\"\n    ]\n}"
      }
    }
  }
}' | jq '.data.service_id' | sed 's/"//g')" >> $APP_HOME/aiip-runtime/airuntime-watcher/src/watcher.conf
echo ""

curl --location --request DELETE "http://$ip_addr:17000/api/auth/cancellationToken" \
--header 'Content-Type: application/json' \
--header "Authorization: $token"

echo ""
for x in {1..360} ; do
    sleep 1s
    printf .
done | pv -pt -i0.2 -s360 -w 80 > /dev/null


# interface
sed -i "s/192.168.1.31/$(hostname -I | awk '{print $1}')/g" $APP_HOME/aiip-runtime/airuntime-watcher/src/watcher.conf
sudo systemctl start airuntime-watcher.service

(crontab -l 2>/dev/null; echo "00 01 * * * sudo rdate -s time.bora.net") | crontab -
(crontab -l 2>/dev/null; echo "00 02 * * * sudo sh /home/airuntime/aiip-runtime/airuntime-watcher/shell/backup_file.sh") | crontab -

echo ""
echo "========================================================================================================"
echo "AI Runtime Watcher(Interface Module) is running."
echo "--------------------------------------------------------------------------------------------------------"
ps -ef | grep -v grep | grep "main.py"
echo "--------------------------------------------------------------------------------------------------------"
sleep 3s

echo "Preparing Sample-Test..."
echo "========================================================================================================"
sleep 5s

# TEST
sudo cp -R $APP_HOME/test/1.2.410.2000010.82.220.12100424023 /data/pacs/input/
sudo mv /data/pacs/input/1.2.410.2000010.82.220.12100424023 /data/pacs/input/RQ1.2.410.2000010.82.220.12100424023
tail -f $APP_HOME/aiip-runtime/airuntime-watcher/logs/airuntime-watcher.log

